
#-----------------------------------------------------------------------

APP       := HardwareApplet
TARGET    := AppletProxyServer
CONFIG    := 
STRIP_FLAG:= N
INCLUDE   += -I../AppletCommon
LIB       += -L/usr/local/mysql/lib/ -lmysqlclient -lssl -lcrypto

#-----------------------------------------------------------------------

include /usr/local/tars/cpp/makefile/makefile.tars

#-----------------------------------------------------------------------
